#!/usr/bin/bash

function makefile_init
{
    if [ -r Makefile ]
    then
        rm -f Makefile
        touch Makefile
    else
        touch Makefile
    fi
    echo "##
## EPITECH PROJECT
## automakefile generated this
## File description:
## Makefile
##" > Makefile
}

if [ -z $1 ]
then
    echo "please enter a configuration file name"
    exit
else
    if [ -r $1 ] && [ -z $2 ]
    then
        makefile_init
    elif [ -z $2 ]
    then
        echo "no valid configuration file"
        exit
    else
        echo "this script only takes one argument"
        exit
    fi
fi

echo "test end of program" >> Makefile